apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gocd-agent-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespace"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/logs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gocd-agent-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: gocd-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: gocd-agent-cluster-role
  apiGroup: ""
