---
# tasks file for gocd-agent

- name: Get gocd repo
  apt_repository:
    repo: "deb https://download.gocd.org /"
    state: present
  become: true
  tags:
    - gocd-apt

- name: Get gocd key
  apt_key:
    url: https://download.gocd.org/GOCD-GPG-KEY.asc
    state: present
  become: true
  tags:
    - gocd-apt

- name: Get gocd agent
  apt:
    name: "go-agent={{ gocd_version }}"
    state: present
    update_cache: true
  become: true
  notify: Start gocd-agent
  tags:
    - gocd-apt

- name: Copy wrapper-config
  template:
    src: templates/usr/share/go-agent/wrapper-config/wrapper-properties.conf.j2
    dest: /usr/share/go-agent/wrapper-config/wrapper-properties.conf
    mode: '0640'
    owner: root
    group: go
  become: true
  notify: Restart gocd-agent
  tags:
    - gocd