Vagrant.configure("2") do |config|
  config.vm.define "gocd" do | gocd |
    gocd.vm.box = "ubuntu/xenial64"
    gocd.vm.network "forwarded_port", guest: 8153, host: 8153
    gocd.vm.provision "ansible" do | ansible |
      ansible.playbook = "site.yml"
    end
    gocd.vm.provider "virtualbox" do | v |
      v.memory = 1024
    end
  end
end
